### ISSUE TITLE
NullReferenceException when typing in breakpoint Actions edit window

### ISSUE THREAD

**Issue by jorisdebock** [bexxx/NamR#1]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: 1.0.21
### Description

When typing in the breakpoint actions edit window it types 2 times the character typed and throws errors (see activity log)
![namr-error](https://cloud.githubusercontent.com/assets/10253291/18143528/adb477e8-6fc2-11e6-87c3-59372e69e798.PNG)
### Steps to recreate
1. Enable NamR extension
2. Add a new breakpoint
3. Open breakpoint edit window 
4. Goto Actions
5. Type something
### Current behavior

see description
### Expected behavior

No errors and only 1 character typed
### Activity log

System.NullReferenceException: Object reference not set to an instance of an object. at NamR.CompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets) at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start() at Microsoft.VisualStudio.Debugger.DebuggerToolWindows.BreakpointSettings.TracepointCompletionHandler.TriggerCompletion() at Microsoft.VisualStudio.Debugger.DebuggerToolWindows.BreakpointSettings.TracepointCompletionHandler.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Diagnostics.UI.Controls.IntellisenseTextBlockAdorner.Exec(Guid& pguidCmdGroup, UInt32 cmdID, UInt32 cmdExecOpt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam) at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

System.InvalidOperationException: Cannot Filter. The session is not yet started. at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Filter() at Microsoft.VisualStudio.Debugger.DebuggerToolWindows.BreakpointSettings.TracepointCompletionHandler.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Diagnostics.UI.Controls.IntellisenseTextBlockAdorner.Exec(Guid& pguidCmdGroup, UInt32 cmdID, UInt32 cmdExecOpt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Debugger.DebuggerToolWindows.BreakpointSettings.BreakpointSettingsControlOleCommandTarget.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.PeekSessionViewModel.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam) at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
### Component error log

empty

**Comment by bexxx** [comment]
Thanks for the details issue description. I could easily repro it and checked in a fix.
Will push this version to vs gallery soon.
