### ISSUE TITLE
Support prefix field identifier with underscore

### ISSUE THREAD

**Issue by micdenny** [bexxx/NamR#7]
Would be great if namr could support the underscore prefix, so when writing a field that starts with `_` namr suggest the name, now it does not, because if you start write something the suggestion disappears.

private MyClass _myClass = new MyClass();

**Comment by bexxx** [comment]
I like to add this a lot although I am not in favor of this naming style. But to support those who do, this will be implemented very soon. 

This should be proposed only for private fields in my opinion.

**Comment by bexxx** [comment]
Published new version of the extension. Let me know if this works for you as expected.

**Comment by micdenny** [comment]
it works, thank you!!
